export const UAE_EMIRATES = [
  'Abu Dhabi',
  'Dubai',
  'Sharjah',
  'Ajman',
  'Umm Al Quwain',
  'Ras Al Khaimah',
  'Fujairah',
];

export const UAE_EMIRATE_AREAS = {
  'Abu Dhabi': [
    'Abu Dhabi City',
    'Al Bateen',
    'Al Danah',
    'Al Khalidiya',
    'Al Karamah',
    'Al Manhal',
    'Al Markaziyah',
    'Al Maryah Island',
    'Al Mushrif',
    'Al Nahyan',
    'Al Raha Beach',
    'Al Rahba',
    'Al Reem Island',
    'Al Reef',
    'Al Samha',
    'Al Shahama',
    'Al Shamkha',
    'Al Wathba',
    'Baniyas',
    'Corniche Area',
    'Khalifa City A',
    'Khalifa City B',
    'Masdar City',
    'Mohammed Bin Zayed City',
    'Saadiyat Island',
    'Yas Island',
    'Al Ain City',
    'Al Jimi',
    'Al Mutaredh',
    'Al Towayya',
    'Hili',
    'Zakher',
    'Madinat Zayed',
    'Liwa',
    'Ruwais',
    'Ghayathi',
    'Sila',
    'Dalma Island',
  ],
  Dubai: [
    'Al Awir',
    'Al Baraha',
    'Al Barsha',
    'Al Barsha 1',
    'Al Barsha 2',
    'Al Barsha 3',
    'Al Barsha South',
    'Al Garhoud',
    'Al Jaddaf',
    'Al Karama',
    'Al Khawaneej',
    'Al Mamzar',
    'Al Mankhool',
    'Al Mizhar',
    'Al Muhaisnah',
    'Al Nahda',
    'Al Qusais',
    'Al Quoz',
    'Al Raffa',
    'Al Raffa Street',
    'Al Ras',
    'Al Rashidiya',
    'Al Rigga',
    'Al Safa',
    'Al Satwa',
    'Al Sufouh',
    'Al Twar',
    'Al Warqa',
    'Al Hamriya',
    'Al Khabeesi',
    'Al Muteena',
    'Hor Al Anz',
    'Naif',
    'Oud Metha',
    'Port Saeed',
    'Arabian Ranches',
    'Barsha Heights',
    'Bluewaters Island',
    'Bur Dubai',
    'Business Bay',
    'City Walk',
    'Deira',
    'Discovery Gardens',
    'Downtown Dubai',
    'Dubai Creek Harbour',
    'Dubai Festival City',
    'Dubai Hills Estate',
    'Dubai Internet City',
    'Dubai Investment Park',
    'Dubai Marina',
    'Dubai Media City',
    'Dubai Silicon Oasis',
    'Dubai South',
    'Dubai Sports City',
    'Dubai Studio City',
    'Emirates Hills',
    'Festival City',
    'Green Community',
    'Hatta',
    'International City',
    'Jebel Ali',
    'Jumeirah',
    'Jumeirah Beach Residence',
    'Jumeirah Lake Towers',
    'Jumeirah Village Circle',
    'Jumeirah Village Triangle',
    'Knowledge Village',
    'Layan Community',
    'Meadows',
    'Mirdif',
    'Motor City',
    'Nad Al Sheba',
    'Palm Jebel Ali',
    'Palm Jumeirah',
    'Remraam',
    'Springs',
    'Tecom',
    'The Greens',
    'The Lakes',
    'The Meadows',
    'The Villa',
    'Town Square',
    'Umm Suqeim',
    'Warsan',
    'World Trade Centre',
  ],
  Sharjah: [
    'Al Dhaid',
    'Al Falaj',
    'Al Fisht',
    'Al Ghubaiba',
    'Al Goaz',
    'Al Hazana',
    'Al Heera',
    'Al Jubail',
    'Al Khan',
    'Al Majaz',
    'Al Mamzar',
    'Al Mirgab',
    'Al Nahda',
    'Al Nasseriya',
    'Al Qadisiya',
    'Al Qasimia',
    'Al Rahmaniya',
    'Al Ramla',
    'Al Ramtha',
    'Al Rolla',
    'Al Sabkha',
    'Al Sajaa',
    'Al Shahba',
    'Al Sharq',
    'Al Taawun',
    'Al Yarmook',
    'Bu Tina',
    'Dasman',
    'Halwan',
    'Industrial Area',
    'Maysaloon',
    'Muwaileh',
    'Muweilah',
    'Rolla',
    'Samnan',
    'Sharjah City',
    'University City',
    'Wasit',
  ],
  Ajman: [
    'Ajman City',
    'Al Bustan',
    'Al Hamidiya',
    'Al Helio',
    'Al Jurf',
    'Al Mowaihat',
    'Al Nuaimiya',
    'Al Owan',
    'Al Rashidiya',
    'Al Rawda',
    'Al Rumailah',
    'Al Zahra',
    'Al Zorah',
    'Emirates City',
    'Garden City',
    'Green City',
    'Industrial Area',
    'Musherief',
    'New Industrial Area',
  ],
  'Umm Al Quwain': [
    'Al Aahad',
    'Al Dar Al Baida',
    'Al Humrah',
    'Al Khor',
    'Al Labsa',
    'Al Maidan',
    'Al Raas',
    'Al Rashidiya',
    'Al Salamah',
    'Al Surra',
    'Falaj Al Mualla',
    'Green Belt',
    'Industrial Area',
    'Old Town',
    'Umm Al Quwain City',
  ],
  'Ras Al Khaimah': [
    'Al Dhait',
    'Al Hamra Village',
    'Al Jazirah Al Hamra',
    'Al Juwais',
    'Al Mamourah',
    'Al Marjan Island',
    'Al Nakheel',
    'Al Qurm',
    'Al Rams',
    'Al Riffa',
    'Al Uraibi',
    'Dafan Al Khor',
    'Dahan',
    'Digdaga',
    'Industrial Area',
    'Julphar Towers',
    'Khuzam',
    'Mina Al Arab',
    'RAK City',
    'Seih Al Burairat',
    'Seih Al Ghubb',
    'Shamal',
  ],
  Fujairah: [
    'Al Faseel',
    'Al Gurfa',
    'Al Hayl',
    'Al Hail',
    'Al Ittihad',
    'Al Owaid',
    'Al Righailat',
    'Al Taween',
    'Dibba Al Fujairah',
    'Dibba Al Hisn',
    'Fujairah City',
    'Gob Dhadna',
    'Industrial Area',
    'Kalba',
    'Madhab',
    'Merashid',
    'Qidfa',
    'Rughaylat',
    'Sakamkam',
    'Sharm',
    'Siji',
  ],
};

export function resolveUaeEmirateKey(emirate) {
  const trimmed = String(emirate || '').trim();
  if (!trimmed) return '';

  if (UAE_EMIRATE_AREAS[trimmed]) return trimmed;

  const lower = trimmed.toLowerCase();
  const match = UAE_EMIRATES.find((name) => name.toLowerCase() === lower);
  if (match) return match;

  const partial = UAE_EMIRATES.find((name) => name.toLowerCase().includes(lower) || lower.includes(name.toLowerCase()));
  return partial || trimmed;
}

export function getUaeAreasForEmirate(emirate) {
  const key = resolveUaeEmirateKey(emirate);
  if (!key) return [];
  return UAE_EMIRATE_AREAS[key] || [];
}

/** Include a previously saved/custom area in the dropdown list. */
export function getUaeAreaOptionsForEmirate(emirate, selectedValue = '') {
  const areas = [...getUaeAreasForEmirate(emirate)].sort((a, b) => a.localeCompare(b, 'en', { sensitivity: 'base' }));
  const custom = String(selectedValue || '').trim();
  if (!custom) return areas;

  const exists = areas.some(
    (area) => area.trim().toLowerCase() === custom.toLowerCase(),
  );
  if (exists) return areas;

  return [custom, ...areas];
}

export function isUaeCountry(country) {
  return String(country || '').trim().toLowerCase() === 'united arab emirates';
}
